version: '3.8'

services:
  ml-backend:
    build:
      context: ./ML_Backend
    ports:
      - "5001:5000"
    env_file:
      - ./ML_Backend/.env
    environment:
      - PORT=5000

  streamlit-frontend:
    build:
      context: ./streamlit_app
    ports:
      - "8080:8080"
    environment:
      - ML_BACKEND_URL=http://ml-backend:5000
    depends_on:
      - ml-backend
    env_file:
      - ./streamlit_app/.env
